var uID = 'ytDownlo'+'ader';
var mUID = uID+''; 
var defaultLang = 'en';
var map = null;

function startup(module) { 

mUID = uID + module.id;

logState(module.settings.log, mUID, 'startup '+ uID);

}

function info() {
    return {
        id: uID,
        name: 'YouTube Video Downlo'+'ader',
        description: i18n('It has never been easier to integrate videos/audios from various platforms into your Holyrics library!<br>' +
    'With this module, you can downlo'+'ad videos/audios practically and efficiently, making online content available for offline use in your presentations or broadcasts.<br>' +
    'Using the powerful yt-dlp, a reliable and modern tool, the module ensures fast downlo'+'ads, customizable quality, and compatibility with various formats.<br>' +
    'All of this directly in Holyrics, with just a few clicks!<br><hr>' +
    '<b>How to use:</b> Click the "Downlo'+'ad Video" icon of the module in the module bar.<br>' +
    'Paste the video link, choose the desired settings, and you’re done! The video will be automatically saved in the configured folder.<br>' +
    '<b>Note:</b> The downlo'+'ad speed may vary depending on your internet connection.<br>' +
    '<b>Requirements:</b> yt-dlp and ffmpeg can be downlo'+'aded through the configuration screen using files generated by the module from the websites:<br>' +
    '<a href="https://github.com/yt-dlp/yt-dlp/releases" target="_blank">"https://github.com/yt-dlp/yt-dlp/releases"</a>, and<br>' +
    '<a href="https://ffmpeg.org/downlo'+'ad.html" target="_blank">https://ffmpeg.org/downlo'+'ad.html</a><br><br><hr><br>' +
    'If the module stops downlo'+'ading videos, the "yt-dlp" version needs to be updated.<br>' +
    'This can happen at any time, so use the module wisely, but have a plan B.<br>')
    }
}


// __SCRIPT_SEPARATOR__ - info:7b226e616d65223a2273657474696e6773227d
function settings(module) {
    return [
        {
            type: 'separator'
        },
        {
            id: 'gpu',
            label: i18n('Dedicated Video Card'),
            type: 'choice',
            allowed_values: [
                { value: '-c:v libx264', label: i18n('None (Default Encoder)') },
                { value: '-c:v h264_nvenc', label: i18n('NVIDIA NVENC') },
                { value: '-c:v h264_qsv', label: i18n('Intel Quick Sync') },
                { value: '-c:v h264_amf', label: i18n('AMD AMF') }
            ],
            default_value: '-c:v libx264',
            description: '<hr>'+i18n('Select the dedicated video card or choose "None" to use the default encoder.')
        },
        {
            name: i18n('Initial Bat'),
            description: '<hr>'+i18n('Use this command to generate the txt file to be renamed to .bat and placed in the files/.modules/ytdownlo'+'ader.bat folder.'),
            button_label: i18n('Generate'),
            type: 'button',
            action: function (evt) {
                createFirstBat(evt,module);
            }
        },
        
        {
            id: 'log',
            label: i18n('Enable log'),
            type: 'boolean',
            onchange: function (obj) {
                logState(obj.input.log, mUID, ' onchange ' + uID);
            }
        }
    ];
}

// __SCRIPT_SEPARATOR__ - info:7b226e616d65223a22616374696f6e73227d
function actions(module) {
    var act = [
        {
            hint: i18n('Downlo'+'ad Web Video and Convert to MP4/MP3'),
            icon: 'ondemand_video',
            action: function () {
                var s = module.settings;
                var inputs = [];
                if (!holyricsPath()) { 
                   showMessage('Downlo'+'ad Web Video', i18n('You need to open any video to complete the module setup'));
                   return;
                }

                inputs.push({
                    type: 'title',
                    name: '<html><b>' + i18n('Downlo'+'ad Video') + '</b>'
                });
                inputs.push({ type: 'separator' });

                inputs.push({
                    id: 'video_url',
                    label: i18n('Video URL'),
                    type: 'string',
                    description: i18n('Paste video URL you want to downlo'+'ad.'),
                    required: true
                });

                inputs.push({
                    id: 'quality',
                    label: i18n('Video Resolution'),
                    type: 'choice',
                    allowed_values: [
                        { value: '2160p', label: i18n('Best (2160p)') },
                        { value: '1080p', label: i18n('Full HD (1080p)') },
                        { value: '720p', label: i18n('HD (720p)') },
                        { value: 'mp3', label: i18n('Audio only') }
                    ],
                    default_value: '1080p',
                    description: i18n('Select the desired quality for the downl' + 'oad.')
                });

                inputs.push({
                    id: 'encoding_speed',
                    label: i18n('Quality/Speed'),
                    type: 'choice',
                    allowed_values: [
                        { value: 'ultrafast', label: i18n('Very Fast (lower quality)') },
                        { value: 'veryfast', label: i18n('Fast') },
                        { value: 'medium', label: i18n('Medium (recommended)') },
                        { value: 'slow', label: i18n('Slow (higher quality)') }
                    ],
                    default_value: '-preset medium -crf 20',
                    description: i18n('Select the balance between encoding quality and speed.')
                });

                inputs.push({
                    id: 'output_folder',
                    label: i18n('Destination Folder'),
                    type: 'string',
                    default_value: '.ModuleDownlo'+'ad',
                    description: i18n('Specify the folder where the downlo'+'aded video will be saved.')
                });

                var q = module.inputSettings('downl' + 'oad_cfgs', inputs);
                if (q !== null) {
                    h.log(mUID, i18n('Downlo'+'ading video with settings: {}', q));
                    createVideoDownFile(q,module);
                }
            }
        }
    ];

    return act;
}


// __SCRIPT_SEPARATOR__ - info:7b226e616d65223a2266756e6374696f6e73227d
function createVideoDownFile(inputs,module) {
    if (!checkOS()) {
      return
    }
    var s = module.settings;
    var cmd_path = s.yt_dlp || '.modules/yt-dlp.exe';
    var basedir = holyricsPath() + 'files/media/';
    var output_folder = inputs.output_folder;
    var destFolder = basedir + (inputs.quality === 'mp3' ? 'audio/' : 'video/') + output_folder;
    var cmdPath = basedir + 'file/' + cmd_path.replace("yt-dlp.exe", "");
    var tmpFolder = basedir + 'tempYTdownlo'+'ader/';

    var video_urls = inputs.video_url.split('|');  
    var quality = inputs.quality || '1080p';

    
    var commandLines = [];
    var ec = 'ec' + 'ho';
    commandLines.push('@ec' + 'ho off');
    commandLines.push('chcp 65001'); 
    commandLines.push('md "' + destFolder + '"');
    commandLines.push('cls');


    var videoCount = video_urls.length;
    
    video_urls.forEach(function (video_url, index) {
        var videoProgress = index + 1; 
        commandLines.push('cd /d "' + cmdPath + '"');
        commandLines.push(ec + ' ' + i18n('Resolution:') + ' ' + inputs.quality);
        commandLines.push(ec + ' ' + i18n('Quality:') + ' ' + inputs.encoding_speed);
        commandLines.push(ec + ' ' + i18n('Encoder:') + ' ' + s.gpu);
        commandLines.push(ec + ' .');
        commandLines.push(ec + ' ' + i18n('Video') + ' ' + videoProgress + '/' +videoCount +': "'+video_url+'"');
        commandLines.push(ec + ' .');
        commandLines.push(ec + ' .');

        var yt_dlp_command;
        if (quality === 'mp3') {
            yt_dlp_command = '"yt-dlp.exe" -o "' + tmpFolder + '/%%(title)s.%%(ext)s" --extract-audio --audio-format mp3 ';
        } else {
            yt_dlp_command = '"yt-dlp.exe" -o "' + tmpFolder + '/%%(title)s.%%(ext)s" -f "bestvideo[height<=' +
            quality.replace('p', '') + ']+bestaudio/best" --merge-output-format mp4';
            // Adiciona a resolução e codec dinamicamente com base na escolha do usuário
            yt_dlp_command += ' -S res:' + quality.replace('p', '') + ',codec:h264';  // Resolução escolhida pelo usuário e codec H.264
            yt_dlp_command += ' --prefer-free-formats';  // Preferir formatos gratuitos

            // Adiciona o uso de cookies do navegador Chrome
            //yt_dlp_command += ' --cookies-from-browser chrome';
    
            // Adiciona parâmetros para recodificação e processamento pós-downlo'+'ad
            yt_dlp_command += ' --recode-video mp4 --postprocessor-args ffmpeg:"' + s.gpu + ' ' + getEncodingParams(inputs,module) + ' -c:a aac -b:a 128k" ';
        }

        yt_dlp_command += '"' + video_url + '"';

        commandLines.push('rd /s/q "' + tmpFolder + '" 2>nul');
        commandLines.push('md "' + tmpFolder + '"');
        commandLines.push(yt_dlp_command);
        commandLines.push('copy /y "' + tmpFolder + '." "' + destFolder + '/" 2>nul');
        commandLines.push('cd /d "' + destFolder + '"');
        commandLines.push('del *.f???.* 2>nul');
        commandLines.push('del *.webm 2>nul');
        commandLines.push('rd /s/q "' + tmpFolder + '" 2>nul');
        commandLines.push(ec + ' .');
        commandLines.push(ec + ' .');
    });

    commandLines.push(ec + ' .');
    commandLines.push(ec + ' ' + i18n('Files saved in folder')+' '+output_folder);
    commandLines.push(ec + ' ===========================================');
    commandLines.push(ec + ' ====    ' + i18n('  Processing complete  ') + '  ==========');
    commandLines.push(ec + ' ===========================================');
    commandLines.push(ec + ' .');
    commandLines.push(ec + ' .');
    commandLines.push('   pause');
        
    h.exportTXT(commandLines.join('\r\n'), {
        name: 'ytdownfile'
    });

    try {
        h.log(mUID, commandLines.join('\r\n'));
        h.executeFile( '.modules/ytdownlo'+'ader.bat');
    } catch (e) {
        h.notificationError(i18n('Error executing BAT file: {}', String(e)), 5);
    }
}

function getEncodingParams(inputs,module) {
    var s = module.settings;
    var gpu = s.gpu || 'libx264'; 
    var encodingSpeedValue = inputs.encoding_speed || 'medium';

    var encodingArgs = '';
    
    if (gpu.contains('libx264')) {
        switch (encodingSpeedValue) {
            case 'ultrafast':
                encodingArgs = '-preset ultrafast -crf 28';
                break;
            case 'veryfast':
                encodingArgs = '-preset veryfast -crf 23';
                break;
            case 'medium':
                encodingArgs = '-preset medium -crf 20';
                break;
            case 'slow':
                encodingArgs = '-preset slow -crf 18';
                break;
            default:
                encodingArgs = '-preset medium -crf 20'; 
        }
    } else if (gpu.contains('h264_nvenc') || gpu.contains('h264_qsv') || gpu.contains('h264_amf')) {        
        switch (encodingSpeedValue) {
            case 'ultrafast':
                encodingArgs = '-preset fast -rc vbr_hq -cq 28';
                break;
            case 'veryfast':
                encodingArgs = '-preset fast -rc vbr_hq -cq 24';
                break;
            case 'medium':
                encodingArgs = '-preset medium -rc vbr_hq -cq 20';
                break;
            case 'slow':
                encodingArgs = '-preset slow -rc vbr_hq -cq 16';
                break;
            default:
                encodingArgs = '-preset medium -rc vbr_hq -cq 20'; 
        }
    } else {
        encodingArgs = '-preset medium -crf 20';
    }
    return encodingArgs;
}

function showMessage(title,message) {
var content = [{ type: 'title',label: title },
              { type: 'separator' },
              { type: 'title',label: message}];
h.input(content);
}

function logState(log, id, caller){ 
    h.log.setEnabled(id, log);
}

function convertBars(path) {
    if (typeof path !== 'string') return '';
    return path.replace(/\\/g, '/');
}

function checkOS() {
   var gVersion = h.hly('GetVersion').data.platform;
   if (gVersion != 'win') {
      showMessage(i18n('This module was designed to run only on the "Windows" operating system'));
      return false
   }
return true
}

function createFirstBat(s,module) {

    if (!checkOS()) {
      return
    }

    if (!holyricsPath()) { 
        showMessage('Downlo'+'ad Web Video', i18n('Before proceeding with the setup, you need to play any video for the module to capture the correct path of your holyrics.'));
        return;
    }    
    var commandLines = [];
    var basePath = holyricsPath() + 'files/media/file/';
    var modulePath = basePath + '.modules'
    var firstBat = basePath +  '.modules/ytdownloa' + 'der.bat';
    var ytdlp = basePath + '.modules/yt-dlp.exe';
    var ffmpeg = basePath + '.modules/ffmpeg.exe';

    ytdlp = ytdlp.replace(/\//g, '\\');
    
    commandLines.push('@ec' + 'ho off');
    commandLines.push('setlocal enabledelayedexpansion');
    commandLines.push('chcp 65001');
    commandLines.push('md "' + modulePath + '"');
    commandLines.push('for /f "tokens=*" %%D in (\'powershell -command "[Environment]::GetFolderPath(\'MyDocuments\')"\') do set DOCUMENTS_PATH=%%D');
    commandLines.push('cls');
    commandLines.push('if not exist "' + firstBat + '" (');
    commandLines.push('   ec' + 'ho ' + i18n('I will open the browser with the downlo'+'ad link for "yt-dlp.exe," the utility used to downlo'+'ad videos.'));
    commandLines.push('   ec' + 'ho ' + i18n('It must be saved in:'));
    commandLines.push('   ec' + 'ho  "' + ytdlp + '"');
    commandLines.push('   ec' + 'ho .');  
    commandLines.push('   ec' + 'ho ' + i18n('Tip: Select the line above and copy it to paste in the downlo'+'ad window!'));  
    commandLines.push('   pause');
    commandLines.push('   start https://github.com/yt-dlp/yt-dlp/releases/latest/downlo'+'ad/yt-dlp.exe');
    commandLines.push('   ec' + 'ho .');  
    commandLines.push('   ec' + 'ho .');  
    commandLines.push('   ec' + 'ho ' + i18n('Downlo'+'ading and installing ffmpeg.exe using the Windows installer.'));
    commandLines.push('   winget install --id=Gyan.FFmpeg -e --verbose');
    commandLines.push('   ec' + 'ho ' + i18n('Copying ffmpeg.exe to the Holyrics folder'));
    commandLines.push('   set BASE_PATH=%LOCALAPPDATA%\\Microsoft\\WinGet\\Packages');
    commandLines.push('   cd /d "!BASE_PATH!"');
    commandLines.push('   set FF_EXE=');
    commandLines.push('   for /f "delims=" %%F in (\'dir /b /s /a-d ffmpeg.exe\') do (');
    commandLines.push('       set FF_EXE=%%F');
    commandLines.push('       goto :CHECK_FOUND');
    commandLines.push('   )');
    commandLines.push('   :CHECK_FOUND');
    commandLines.push('   if exist "!FF_EXE!" (');
    commandLines.push('       if not exist "' + basePath + '" mkdir "' + basePath + '"');
    commandLines.push('       copy "!FF_EXE!" "' + ffmpeg + '" /y');
    commandLines.push('   cls');  
    commandLines.push('       if errorlevel 1 (');
    commandLines.push('           ec'+'ho ' + i18n('Failed to copy ffmpeg.exe.'));
    commandLines.push('           pause');
    commandLines.push('           ex' + 'it /b 1');
    commandLines.push('       ) else (');
    commandLines.push('           ec'+'ho ' + i18n('FFmpeg successfully copied to "') + ffmpeg + i18n('".'));
    commandLines.push('       )');
    commandLines.push('   ) else (');
    commandLines.push('       ec'+'ho ' + i18n('FFmpeg executable not found in the expected path.'));
    commandLines.push('       pause');
    commandLines.push('       ex' + 'it /b 1');
    commandLines.push('   )');
    commandLines.push('   copy /y "%DOCUMENTS_PATH%\\Holyrics\\js\\ytdownlo'+'ader.bat" "' + firstBat + '"');
    commandLines.push('   cls');  
    commandLines.push('   ec' + 'ho ' + i18n('Operation completed.'));
    commandLines.push('   pause');
    commandLines.push('   ex'+'it');
    commandLines.push(') else (');
    commandLines.push('   copy /y "%DOCUMENTS_PATH%\\Holyrics\\js\\ytdownfile.txt" "%DOCUMENTS_PATH%\\Holyrics\\js\\ytdownfile.bat"');
    commandLines.push('   del "%DOCUMENTS_PATH%\\Holyrics\\js\\ytdownfile.txt"');
    commandLines.push('   call "%DOCUMENTS_PATH%\\Holyrics\\js\\ytdownfile.bat"');
    commandLines.push('   del "%DOCUMENTS_PATH%\\Holyrics\\js\\ytdownfile.bat"');
    commandLines.push(')');

    h.log('=========================================================================');
    h.log(i18n('Open the location of the file indicated in the message below.'));
    h.log(i18n('You need to rename it to "ytdownlo'+'ader.bat"'));
    h.log(i18n('After renaming, double-click to execute\n' +
               'and follow the instructions on the screen, as all module\n' +
               'configuration will be done by this file.'));
    h.log('=========================================================================');
    h.exportTXT(commandLines.join('\r\n'), {
        name: 'ytdownlo'+'ader',
    });
}

// __SCRIPT_SEPARATOR__ - info:7b226e616d65223a2274726967676572227d
function holyricsPath(path) {
var key = mUID+'_path';
if (path) {
    var f = path;
    var p = f.indexOf('files');
    var pathHolyrics = f.substring(0, p);
    h.store(key, convertBars(pathHolyrics));
    showMessage('Downlo'+'ad Web Video', i18n('Holyrics location on the computer successfully completed!'));
    }
   var result = h.restore(key);
   if (!result && h.isMinimumVersion('2.24.0')) {
      var pathHolyrics = convertBars(h.hly('GetVersion').data.baseDir + '/holyrics/');
      h.store(key, convertBars(pathHolyrics));  
      result = pathHolyrics;
      h.log(mUID, '{%t} Holyrics base path ajustado para {}', result);
      }
   h.log(mUID, '{%t} Holyrics base path {}', result);
return result
}
 
function triggers(module) {
  var arr = [];
  if (!h.isMinimumVersion('2.24.0')) {
    h.log(mUID,'{%t} Versão inferior à 2.24, criando trigger');
    arr.push({
      id: "capture_holyrics_path" + uID,
      when: "displaying",
      item: "any_video",
      action: function(obj) {
          if (holyricsPath()) {
             return;
          }
          holyricsPath(obj.file_path);
          }
       });
  }
  return arr; 
}
// __SCRIPT_SEPARATOR__ - info:7b226e616d65223a226931386e227d
function i18n_getAllItems() {
    var arr = [];

arr.push({
    en: 'Files saved in folder',
    pt: 'Arquivos salvos na pasta',
    ru: 'Файлы сохранены в папке',
    es: 'Archivos guardados en la carpeta',
    it: 'File salvati nella cartella'
});

arr.push({
    en: 'This module was designed to run only on the "Windows" operating system',
    pt: 'Este módulo foi preparado para ser executado apenas no sistema operacional "Windows"',
    ru: 'Этот модуль был разработан для работы только на операционной системе "Windows"',
    es: 'Este módulo fue diseñado para ejecutarse solo en el sistema operativo "Windows"',
    it: 'Questo modulo è stato progettato per funzionare solo nel sistema operativo "Windows"'
});

arr.push({
    en: 'Holyrics location on the computer successfully completed!',
    pt: 'Localização do Holyrics no computador realizada com sucesso!',
    ru: 'Местоположение Holyrics на компьютере успешно завершено!',
    es: '¡Ubicación de Holyrics en el ordenador completada con éxito!',
    it: 'Posizione di Holyrics sul computer completata con successo!'
});

arr.push({
    en: 'Before proceeding with the setup, you need to play any video for the module to capture the correct path of your holyrics.',
    pt: 'Antes de prosseguir com a configuração, você precisa executar um vídeo qualquer para o módulo capturar o caminho correto do seu holyrics.',
    ru: 'Перед продолжением настройки вам нужно воспроизвести любое видео, чтобы модуль захватил правильный путь к вашему holyrics.',
    es: 'Antes de continuar con la configuración, necesitas reproducir cualquier video para que el módulo capture la ruta correcta de tus holyrics.',
    it: 'Prima di procedere con la configurazione, devi riprodurre un video qualsiasi affinché il modulo catturi il percorso corretto dei tuoi holyrics.'
});

arr.push({
    en: 'You need to open any video to complete the module setup',
    pt: 'Você precisa abrir um vídeo qualquer para completar a configuração do módulo',
    ru: 'Необходимо открыть любое видео для завершения настройки модуля',
    es: 'Necesitas abrir cualquier video para completar la configuración del módulo',
    it: 'È necessario aprire qualsiasi video per completare la configurazione del modulo'
});

arr.push({
    en: 'About',
    pt: 'Sobre',
    ru: 'О',
    es: 'Acerca de',
    it: 'Informazioni'
});
arr.push({
    en: 'Path to "holyrics.exe"',
    pt: 'Caminho para "holyrics.exe"',
    ru: 'Путь к "holyrics.exe"',
    es: 'Ruta a "holyrics.exe"',
    it: 'Percorso per "holyrics.exe"'
});
arr.push({
    en: 'Check the folder where your holyrics is located. This will only serve to know where the video and audio folders are to place the downlo'+'aded file correctly.',
    pt: 'Verifique a pasta onde está localizado o holyrics. Isso servirá apenas para saber onde estão as pastas de vídeo e áudio para colocar o arquivo baixado corretamente.',
    ru: 'Проверьте папку, где находится ваш holyrics. Это нужно только для определения папок видео и аудио, чтобы правильно разместить загруженный файл.',
    es: 'Verifique la carpeta donde se encuentra su holyrics. Esto solo servirá para saber dónde están las carpetas de video y audio para colocar correctamente el archivo descargado.',
    it: 'Controlla la cartella in cui si trova il tuo holyrics. Questo servirà solo per sapere dove si trovano le cartelle video e audio per posizionare correttamente il file scaricato.'
});
arr.push({
    en: 'Relative path to "yt-dlp.exe" in the file folder',
    pt: 'Caminho relativo para "yt-dlp.exe" na pasta file',
    ru: 'Относительный путь к "yt-dlp.exe" в папке file',
    es: 'Ruta relativa a "yt-dlp.exe" en la carpeta file',
    it: 'Percorso relativo a "yt-dlp.exe" nella cartella file'
});
arr.push({
    en: 'Enter the path where you placed the yt-dlp.exe file. It needs to be in the Holyrics file folder. If possible, leave it as default.',
    pt: 'Digite o caminho onde você colocou o arquivo yt-dlp.exe. Ele precisa estar na pasta file do Holyrics. Se possível, deixe como padrão.',
    ru: 'Введите путь, где вы разместили файл yt-dlp.exe. Он должен находиться в папке file Holyrics. Если возможно, оставьте его по умолчанию.',
    es: 'Ingrese la ruta donde colocó el archivo yt-dlp.exe. Debe estar en la carpeta file de Holyrics. Si es posible, déjelo como predeterminado.',
    it: 'Inserisci il percorso in cui hai posizionato il file yt-dlp.exe. Deve trovarsi nella cartella file di Holyrics. Se possibile, lascialo come predefinito.'
});
arr.push({
    en: 'Relative path to "ffmpeg.exe" in the file folder',
    pt: 'Caminho relativo para "ffmpeg.exe" na pasta file',
    ru: 'Относительный путь к "ffmpeg.exe" в папке file',
    es: 'Ruta relativa a "ffmpeg.exe" en la carpeta file',
    it: 'Percorso relativo a "ffmpeg.exe" nella cartella file'
});
arr.push({
    en: 'Enter the path where you placed the ffmpeg.exe file, version 7.1 or higher. It needs to be in the Holyrics file folder. If possible, leave it as default.',
    pt: 'Digite o caminho onde você colocou o arquivo ffmpeg.exe, versão 7.1 ou superior. Ele precisa estar na pasta file do Holyrics. Se possível, deixe como padrão.',
    ru: 'Введите путь, где вы разместили файл ffmpeg.exe версии 7.1 или выше. Он должен находиться в папке file Holyrics. Если возможно, оставьте его по умолчанию.',
    es: 'Ingrese la ruta donde colocó el archivo ffmpeg.exe, versión 7.1 o superior. Debe estar en la carpeta file de Holyrics. Si es posible, déjelo como predeterminado.',
    it: 'Inserisci il percorso in cui hai posizionato il file ffmpeg.exe, versione 7.1 o successiva. Deve trovarsi nella cartella file di Holyrics. Se possibile, lascialo come predefinito.'
});
arr.push({
    en: 'Relative path to "ytdownlo'+'ader.bat" in the file folder',
    pt: 'Caminho relativo para "ytdownlo'+'ader.bat" na pasta file',
    ru: 'Относительный путь к "ytdownlo'+'ader.bat" в папке file',
    es: 'Ruta relativa a "ytdownlo'+'ader.bat" en la carpeta file',
    it: 'Percorso relativo a "ytdownlo'+'ader.bat" nella cartella file'
});
arr.push({
    en: 'Enter the path where you placed the ytdownlo'+'ader.bat file. It needs to be in the Holyrics file folder. If possible, leave it as default.',
    pt: 'Digite o caminho onde você colocou o arquivo ytdownlo'+'ader.bat. Ele precisa estar na pasta file do Holyrics. Se possível, deixe como padrão.',
    ru: 'Введите путь, где вы разместили файл ytdownlo'+'ader.bat. Он должен находиться в папке file Holyrics. Если возможно, оставьте его по умолчанию.',
    es: 'Ingrese la ruta donde colocó el archivo ytdownlo'+'ader.bat. Debe estar en la carpeta file de Holyrics. Si es posible, déjelo como predeterminado.',
    it: 'Inserisci il percorso in cui hai posizionato il file ytdownlo'+'ader.bat. Deve trovarsi nella cartella file di Holyrics. Se possibile, lascialo come predefinito.'
});

arr.push({
    en: 'Dedicated Video Card',
    pt: 'Placa de Vídeo Dedicada',
    ru: 'Выделенная видеокарта',
    es: 'Tarjeta de Video Dedicada',
    it: 'Scheda Video Dedicata'
});
arr.push({
    en: 'None (Default Encoder)',
    pt: 'Nenhuma (Codificador Padrão)',
    ru: 'Нет (кодировщик по умолчанию)',
    es: 'Ninguna (Codificador Predeterminado)',
    it: 'Nessuno (Codificatore Predefinito)'
});
arr.push({
    en: 'NVIDIA NVENC',
    pt: 'NVIDIA NVENC',
    ru: 'NVIDIA NVENC',
    es: 'NVIDIA NVENC',
    it: 'NVIDIA NVENC'
});
arr.push({
    en: 'Intel Quick Sync',
    pt: 'Intel Quick Sync',
    ru: 'Intel Quick Sync',
    es: 'Intel Quick Sync',
    it: 'Intel Quick Sync'
});
arr.push({
    en: 'AMD AMF',
    pt: 'AMD AMF',
    ru: 'AMD AMF',
    es: 'AMD AMF',
    it: 'AMD AMF'
});
arr.push({
    en: 'Select the dedicated video card or choose "None" to use the default encoder.',
    pt: 'Selecione a placa de vídeo dedicada ou escolha "Nenhuma" para usar o codificador padrão.',
    ru: 'Выберите выделенную видеокарту или выберите "Нет", чтобы использовать кодировщик по умолчанию.',
    es: 'Seleccione la tarjeta de video dedicada o elija "Ninguna" para usar el codificador predeterminado.',
    it: 'Seleziona la scheda video dedicata o scegli "Nessuno" per utilizzare il codificatore predefinito.'
});
arr.push({
    en: 'Initial Bat',
    pt: 'Bat Inicial',
    ru: 'Начальный Bat',
    es: 'Bat Inicial',
    it: 'Bat Iniziale'
});
arr.push({
    en: 'Use this command to generate the txt file to be renamed to .bat and placed in the .modules/ytdownlo'+'ader.bat folder.',
    pt: 'Use este comando para gerar o arquivo txt a ser renomeado para .bat e colocado na pasta .modules/ytdownlo'+'ader.bat.',
    ru: 'Используйте эту команду для создания txt-файла, который нужно переименовать в .bat и поместить в папку .modules/ytdownlo'+'ader.bat.',
    es: 'Use este comando para generar el archivo txt para renombrarlo a .bat y colocarlo en la carpeta .modules/ytdownlo'+'ader.bat.',
    it: 'Usa questo comando per generare il file txt da rinominare in .bat e posizionare nella cartella .modules/ytdownlo'+'ader.bat.'
});
arr.push({
    en: 'Generate',
    pt: 'Gerar',
    ru: 'Сгенерировать',
    es: 'Generar',
    it: 'Generare'
});
arr.push({
    en: 'Enable log',
    pt: 'Ativar log',
    ru: 'Включить лог',
    es: 'Habilitar registro',
    it: 'Abilita registro'
});

arr.push({
    en: 'Downlo'+'ad Web Video and Convert to MP4/MP3',
    pt: 'Baixar Vídeo da Web e converter para MP4/MP3',
    ru: 'Скачать видео из интернета и конвертировать в MP4/MP3',
    es: 'Descargar video web y convertir a MP4/MP3',
    it: 'Scarica video dal web e converti in MP4/MP3'
});

arr.push({
    en: 'Downlo'+'ad Video',
    pt: 'Baixar Vídeo',
    ru: 'Скачать видео',
    es: 'Descargar Video',
    it: 'Scarica Video'
});

arr.push({
    en: 'Video URL',
    pt: 'URL do Vídeo',
    ru: 'URL видео',
    es: 'URL del video',
    it: 'URL del video'
});
arr.push({
    en: 'Paste video URL you want to downlo'+'ad.',
    pt: 'Cole a URL do vídeo que você deseja baixar.',
    ru: 'Вставьте URL видео, которое вы хотите скачать.',
    es: 'Pega la URL del video que deseas descargar.',
    it: 'Incolla l\'URL del video che desideri scaricare.'
});
arr.push({
    en: 'Video Resolution',
    pt: 'Resolução do Vídeo',
    ru: 'Разрешение видео',
    es: 'Resolución del video',
    it: 'Risoluzione video'
});
arr.push({
    en: 'Best (2160p)',
    pt: 'Melhor (2160p)',
    ru: 'Лучшее (2160p)',
    es: 'Mejor (2160p)',
    it: 'Migliore (2160p)'
});
arr.push({
    en: 'Full HD (1080p)',
    pt: 'Full HD (1080p)',
    ru: 'Полный HD (1080p)',
    es: 'Full HD (1080p)',
    it: 'Full HD (1080p)'
});
arr.push({
    en: 'HD (720p)',
    pt: 'HD (720p)',
    ru: 'HD (720p)',
    es: 'HD (720p)',
    it: 'HD (720p)'
});
arr.push({
    en: 'Audio only',
    pt: 'Somente áudio',
    ru: 'Только аудио',
    es: 'Solo audio',
    it: 'Solo audio'
});
arr.push({
    en: 'Select the desired quality for the downlo'+'ad.',
    pt: 'Selecione a qualidade desejada para o downlo'+'ad.',
    ru: 'Выберите желаемое качество для загрузки.',
    es: 'Seleccione la calidad deseada para la descarga.',
    it: 'Seleziona la qualità desiderata per il downlo'+'ad.'
});
arr.push({
    en: 'Quality/Speed',
    pt: 'Qualidade/Velocidade',
    ru: 'Качество/Скорость',
    es: 'Calidad/Velocidad',
    it: 'Qualità/Velocità'
});
arr.push({
    en: 'Very Fast (lower quality)',
    pt: 'Muito Rápido (menor qualidade)',
    ru: 'Очень быстро (низкое качество)',
    es: 'Muy rápido (calidad inferior)',
    it: 'Molto veloce (qualità inferiore)'
});
arr.push({
    en: 'Fast',
    pt: 'Rápido',
    ru: 'Быстро',
    es: 'Rápido',
    it: 'Veloce'
});
arr.push({
    en: 'Medium (recommended)',
    pt: 'Médio (recomendado)',
    ru: 'Среднее (рекомендуется)',
    es: 'Medio (recomendado)',
    it: 'Medio (consigliato)'
});
arr.push({
    en: 'Slow (higher quality)',
    pt: 'Lento (maior qualidade)',
    ru: 'Медленно (высокое качество)',
    es: 'Lento (mayor calidad)',
    it: 'Lento (qualità superiore)'
});
arr.push({
    en: 'Select the balance between encoding quality and speed.',
    pt: 'Selecione o equilíbrio entre qualidade e velocidade de codificação.',
    ru: 'Выберите баланс между качеством и скоростью кодирования.',
    es: 'Seleccione el equilibrio entre calidad y velocidad de codificación.',
    it: 'Seleziona l\'equilibrio tra qualità e velocità di codifica.'
});
arr.push({
    en: 'Destination Folder',
    pt: 'Pasta de Destino',
    ru: 'Папка назначения',
    es: 'Carpeta de destino',
    it: 'Cartella di destinazione'
});
arr.push({
    en: 'Specify the folder where the downlo'+'aded video will be saved.',
    pt: 'Especifique a pasta onde o vídeo baixado será salvo.',
    ru: 'Укажите папку, в которой будет сохранено загруженное видео.',
    es: 'Especifique la carpeta donde se guardará el video descargado.',
    it: 'Specifica la cartella in cui verrà salvato il video scaricato.'
});
arr.push({
    en: 'Downlo'+'ading video with settings: {}',
    pt: 'Baixando vídeo com as configurações: {}',
    ru: 'Скачивание видео с настройками: {}',
    es: 'Descargando video con configuraciones: {}',
    it: 'Scaricamento video con impostazioni: {}'
});
arr.push({
    en: 'URL: "{}"',
    pt: 'URL: "{}"',
    ru: 'URL: "{}"',
    es: 'URL: "{}"',
    it: 'URL: "{}"'
});
arr.push({
    en: 'Resolution: {}',
    pt: 'Resolução: {}',
    ru: 'Разрешение: {}',
    es: 'Resolución: {}',
    it: 'Risoluzione: {}'
});
arr.push({
    en: 'Quality: {}',
    pt: 'Qualidade: {}',
    ru: 'Качество: {}',
    es: 'Calidad: {}',
    it: 'Qualità: {}'
});
arr.push({
    en: 'Encoder: {}',
    pt: 'Codificador: {}',
    ru: 'Кодировщик: {}',
    es: 'Codificador: {}',
    it: 'Encoder: {}'
});
arr.push({
    en: 'File saved in folder {}',
    pt: 'Arquivo salvo na pasta {}',
    ru: 'Файл сохранён в папке {}',
    es: 'Archivo guardado en la carpeta {}',
    it: 'File salvato nella cartella {}'
});
arr.push({
    en: '  Processing complete  ',
    pt: 'Processamento concluído',
    ru: '  Обработка завершена  ',
    es: 'Procesamiento completo ',
    it: 'Elaborazione completata'
});
arr.push({
    en: 'Error executing BAT file: {}',
    pt: 'Erro ao executar o arquivo BAT: {}',
    ru: 'Ошибка выполнения файла BAT: {}',
    es: 'Error al ejecutar el archivo BAT: {}',
    it: 'Errore nell\'esecuzione del file BAT: {}'
});

arr.push({
    en: 'I will open the browser with the downlo'+'ad link for "yt-dlp.exe," the utility used to downlo'+'ad videos.',
    pt: 'Vou abrir o navegador com o link de downlo'+'ad do "yt-dlp.exe", que é o utilitário que baixa os vídeos.',
    ru: 'Я открою браузер со ссылкой на загрузку "yt-dlp.exe", утилиты для загрузки видео.',
    es: 'Abriré el navegador con el enlace de descarga de "yt-dlp.exe," la utilidad utilizada para descargar videos.',
    it: 'Aprirò il browser con il link per scaricare "yt-dlp.exe", l\'utilità utilizzata per scaricare video.'
});
arr.push({
    en: 'It must be saved in:',
    pt: 'Ele deve ser salvo em:',
    ru: 'Его необходимо сохранить в:',
    es: 'Debe guardarse en:',
    it: 'Deve essere salvato in:'
});
arr.push({
    en: 'Tip: Select the line above and copy it to paste in the downlo'+'ad window!',
    pt: 'Uma dica: selecione essa linha aí de cima e copie para colar na janela de downlo'+'ad!',
    ru: 'Совет: выберите строку выше и скопируйте её, чтобы вставить в окно загрузки!',
    es: 'Consejo: ¡Selecciona la línea de arriba y cópiala para pegarla en la ventana de descarga!',
    it: 'Suggerimento: seleziona la riga sopra e copiala per incollarla nella finestra di downlo'+'ad!'
});
arr.push({
    en: 'Downlo'+'ading and installing ffmpeg.exe using the Windows installer.',
    pt: 'Baixando e instalando o ffmpeg.exe usando o instalador do Windows.',
    ru: 'Скачивание и установка ffmpeg.exe с использованием установщика Windows.',
    es: 'Descargando e instalando ffmpeg.exe usando el instalador de Windows.',
    it: 'Scaricando e installando ffmpeg.exe utilizzando l\'installatore di Windows.'
});
arr.push({
    en: 'Copying ffmpeg.exe to the Holyrics folder',
    pt: 'Copiando ffmpeg.exe para a pasta do Holyrics',
    ru: 'Копирование ffmpeg.exe в папку Holyrics',
    es: 'Copiando ffmpeg.exe a la carpeta de Holyrics',
    it: 'Copia di ffmpeg.exe nella cartella di Holyrics'
});
arr.push({
    en: 'Failed to copy ffmpeg.exe.',
    pt: 'Falha ao copiar ffmpeg.exe.',
    ru: 'Не удалось скопировать ffmpeg.exe.',
    es: 'Error al copiar ffmpeg.exe.',
    it: 'Copia di ffmpeg.exe non riuscita.'
});
arr.push({
    en: 'FFmpeg successfully copied to "{path}".',
    pt: 'FFmpeg copiado com sucesso para "{path}".',
    ru: 'FFmpeg успешно скопирован в "{path}".',
    es: 'FFmpeg copiado ex'+'itosamente en "{path}".',
    it: 'FFmpeg copiato con successo in "{path}".'
});
arr.push({
    en: 'FFmpeg executable not found in the expected path.',
    pt: 'Executável FFmpeg não encontrado no caminho esperado.',
    ru: 'Исполняемый файл FFmpeg не найден по ожидаемому пути.',
    es: 'Ejecutable de FFmpeg no encontrado en la ruta esperada.',
    it: 'File eseguibile FFmpeg non trovato nel percorso previsto.'
});
arr.push({
    en: 'Operation completed.',
    pt: 'Operação concluída.',
    ru: 'Операция завершена.',
    es: 'Operación completada.',
    it: 'Operazione completata.'
});
arr.push({
    en: 'Open the folder of the file indicated on the right\nside of the screen "ytdownlo'+'ader.txt".',
    pt: 'Abra a pasta do arquivo indicado no lado direito\nda tela "ytdownlo'+'ader.txt".',
    ru: 'Откройте папку с файлом, указанным на правой\nстороне экрана "ytdownlo'+'ader.txt".',
    es: 'Abre la carpeta del archivo indicado en el lado\n derec'+'ho de la pantalla "ytdownlo'+'ader.txt".',
    it: 'Apri la cartella del file indicato sul lato destro\ndello schermo "ytdownlo'+'ader.txt".'
});
arr.push({
    en: 'You need to rename it to "ytdownlo'+'ader.bat".',
    pt: 'Você precisa renomeá-lo para "ytdownlo'+'ader.bat".',
    ru: 'Вам нужно переименовать его в "ytdownlo'+'ader.bat".',
    es: 'Debes renombrarlo a "ytdownlo'+'ader.bat".',
    it: 'Devi rinominarlo in "ytdownlo'+'ader.bat".'
});
arr.push({
    en: 'After that, double-click it to run it for the\nfirst time and copy it to the correct Holyrics folder.',
    pt: 'Depois disso, clique duas vezes para executá-lo\npela primeira vez e copiá-lo para a pasta correta do Holyrics.',
    ru: 'После этого дважды щелкните по нему, чтобы\nзапустить его в первый раз и скопировать в правильную папку Holyrics.',
    es: 'Después de eso, haz doble clic para ejecutarlo\npor primera vez y copiarlo a la carpeta correcta de Holyrics.',
    it: 'Dopodiché, fai doppio clic per eseguirlo\nper la prima volta e copiarlo nella cartella corretta di Holyrics.'
});


arr.push({
    en: 'Check the folder where your holyrics is located. This will only serve to know where the video and audio folders are to place the downlo'+'aded file correctly.',
    pt: 'Verifique a pasta onde seu holyrics está localizado. Isso servirá apenas para saber onde estão as pastas de vídeo e áudio para colocar o arquivo baixado corretamente.',
    ru: 'Проверьте папку, где находится ваш holyrics. Это нужно только для того, чтобы узнать, где находятся папки видео и аудио, чтобы правильно разместить загруженный файл.',
    es: 'Verifica la carpeta donde se encuentra tu holyrics. Esto solo servirá para saber dónde están las carpetas de video y audio para colocar el archivo descargado correctamente.',
    it: 'Controlla la cartella in cui si trova il tuo holyrics. Questo servirà solo a sapere dove si trovano le cartelle video e audio per posizionare correttamente il file scaricato.'
});
arr.push({
    en: 'Relative path to "yt-dlp.exe" in the "files" folder',
    pt: 'Caminho relativo para "yt-dlp.exe" na pasta "files"',
    ru: 'Относительный путь к "yt-dlp.exe" в папке "files"',
    es: 'Ruta relativa a "yt-dlp.exe" en la carpeta "files"',
    it: 'Percorso relativo a "yt-dlp.exe" nella cartella "files"'
});
arr.push({
    en: 'Enter the path where you placed the yt-dlp.exe file. It needs to be in the Holyrics "files" folder. If possible, leave it as default.',
    pt: 'Digite o caminho onde você colocou o arquivo yt-dlp.exe. Ele precisa estar na pasta "files" do Holyrics. Se possível, deixe como padrão.',
    ru: 'Введите путь, где вы разместили файл yt-dlp.exe. Он должен находиться в папке "files" Holyrics. Если возможно, оставьте значение по умолчанию.',
    es: 'Ingresa la ruta donde colocaste el archivo yt-dlp.exe. Debe estar en la carpeta "files" de Holyrics. Si es posible, déjalo como predeterminado.',
    it: 'Inserisci il percorso in cui hai posizionato il file yt-dlp.exe. Deve trovarsi nella cartella "files" di Holyrics. Se possibile, lasciare come predefinito.'
});
arr.push({
    en: 'Relative path to "ffmpeg.exe" in the "files" folder',
    pt: 'Caminho relativo para "ffmpeg.exe" na pasta "files"',
    ru: 'Относительный путь к "ffmpeg.exe" в папке "files"',
    es: 'Ruta relativa a "ffmpeg.exe" en la carpeta "files"',
    it: 'Percorso relativo a "ffmpeg.exe" nella cartella "files"'
});
arr.push({
    en: 'Enter the path where you placed the ffmpeg.exe file, version 7.1 or higher. It needs to be in the Holyrics "files" folder. If possible, leave it as default.',
    pt: 'Digite o caminho onde você colocou o arquivo ffmpeg.exe, versão 7.1 ou superior. Ele precisa estar na pasta "files" do Holyrics. Se possível, deixe como padrão.',
    ru: 'Введите путь, где вы разместили файл ffmpeg.exe версии 7.1 или выше. Он должен находиться в папке "files" Holyrics. Если возможно, оставьте значение по умолчанию.',
    es: 'Ingresa la ruta donde colocaste el archivo ffmpeg.exe, versión 7.1 o superior. Debe estar en la carpeta "files" de Holyrics. Si es posible, déjalo como predeterminado.',
    it: 'Inserisci il percorso in cui hai posizionato il file ffmpeg.exe, versione 7.1 o superiore. Deve trovarsi nella cartella "files" di Holyrics. Se possibile, lasciare come predefinito.'
});
arr.push({
    en: 'Relative path to "ytdownlo'+'ader.bat" in the "files" folder',
    pt: 'Caminho relativo para "ytdownlo'+'ader.bat" na pasta "files"',
    ru: 'Относительный путь к "ytdownlo'+'ader.bat" в папке "files"',
    es: 'Ruta relativa a "ytdownlo'+'ader.bat" en la carpeta "files"',
    it: 'Percorso relativo a "ytdownlo'+'ader.bat" nella cartella "files"'
});
arr.push({
    en: 'Enter the path where you placed the ytdownlo'+'ader.bat file. It needs to be in the Holyrics "files" folder. If possible, leave it as default.',
    pt: 'Digite o caminho onde você colocou o arquivo ytdownlo'+'ader.bat. Ele precisa estar na pasta "files" do Holyrics. Se possível, deixe como padrão.',
    ru: 'Введите путь, где вы разместили файл ytdownlo'+'ader.bat. Он должен находиться в папке "files" Holyrics. Если возможно, оставьте значение по умолчанию.',
    es: 'Ingresa la ruta donde colocaste el archivo ytdownlo'+'ader.bat. Debe estar en la carpeta "files" de Holyrics. Si es posible, déjalo como predeterminado.',
    it: 'Inserisci il percorso in cui hai posizionato il file ytdownlo'+'ader.bat. Deve trovarsi nella cartella "files" di Holyrics. Se possibile, lasciare come predefinito.'
});
arr.push({
    en: 'Use this command to generate the txt file to be renamed to .bat and placed in the files/.modules/ytdownlo'+'ader.bat folder.',
    pt: 'Use este comando para gerar o arquivo txt que deve ser renomeado para .bat e colocado na pasta files/.modules/ytdownlo'+'ader.bat.',
    ru: 'Используйте эту команду для создания txt-файла, который нужно переименовать в .bat и разместить в папке files/.modules/ytdownlo'+'ader.bat.',
    es: 'Usa este comando para generar el archivo txt que debe renombrarse a .bat y colocarse en la carpeta files/.modules/ytdownlo'+'ader.bat.',
    it: 'Usa questo comando per generare il file txt da rinominare in .bat e posizionare nella cartella files/.modules/ytdownlo'+'ader.bat.'
});
arr.push({
    en: 'Close service window on finish',
    pt: 'Fechar a janela de serviço ao terminar',
    ru: 'Закрыть окно сервиса после завершения',
    es: 'Cerrar la ventana de servicio al finalizar',
    it: 'Chiudi la finestra di servizio al termine'
});

arr.push({
    en: 'Open the location of the file indicated in the message below.',
    pt: 'Abra o local do arquivo indicado na mensagem abaixo.',
    ru: 'Откройте расположение файла, указанного в сообщении ниже.',
    es: 'Abra la ubicación del archivo indicado en el mensaje a continuación.',
    it: 'Apri la posizione del file indicato nel messaggio qui sotto.'
});

arr.push({
    en: 'You need to rename it to "ytdownlo'+'ader.bat"',
    pt: 'Você precisa renomear ele para "ytdownlo'+'ader.bat"',
    ru: 'Вам нужно переименовать его в "ytdownlo'+'ader.bat"',
    es: 'Necesitas renombrarlo a "ytdownlo'+'ader.bat"',
    it: 'Devi rinominarlo in "ytdownlo'+'ader.bat"'
});

arr.push({
    en: 'After renaming, double-click to execute\n' + 
        'and follow the instructions on the screen, as all module\n' +
        'configuration will be done by this file.',
    pt: 'Depois de renomear, dê 2 cliques para executar\n' + 
        'e siga as instruções da tela, pois toda a configuração\n' +
        'do módulo será realizada por este arquivo.',
    ru: 'После переименования дважды щелкните, чтобы выполнить\n' + 
        'и следуйте инструкциям на экране, так как вся настройка\n' +
        'модуля будет выполнена этим файлом.',
    es: 'Después de renombrarlo, haz doble clic para ejecutarlo\n' +
        'y sigue las instrucciones en pantalla, ya que toda la configuración\n' +
        'del módulo se realizará con este archivo.',
    it: 'Dopo averlo rinominato, fai doppio clic per eseguire\n' + 
        'e segui le istruzioni sullo schermo, poiché tutta la configurazione\n' +
        'del modulo sarà eseguita da questo file.'
});

arr.push({
    en: 'It has never been easier to integrate videos/audios from various platforms into your Holyrics library!<br>' +
        'With this module, you can downlo'+'ad videos/audios practically and efficiently, making online content available for offline use in your presentations or broadcasts.<br>' +
        'Using the powerful yt-dlp, a reliable and modern tool, the module ensures fast downlo'+'ads, customizable quality, and compatibility with various formats.<br>' +
        'All of this directly in Holyrics, with just a few clicks!<br><hr>' +
        '<b>How to use:</b> Click the "Downlo'+'ad Video" icon of the module in the module bar.<br>' +
        'Paste the video link, choose the desired settings, and you’re done! The video will be automatically saved in the configured folder.<br>' +
        '<b>Note:</b> The downlo'+'ad speed may vary depending on your internet connection.<br>' +
        '<b>Requirements:</b> yt-dlp and ffmpeg can be downlo'+'aded through the configuration screen using files generated by the module from the websites:<br>' +
        '<a href="https://github.com/yt-dlp/yt-dlp/releases" target="_blank">"https://github.com/yt-dlp/yt-dlp/releases"</a>, and<br>' +
        '<a href="https://ffmpeg.org/downlo'+'ad.html" target="_blank">https://ffmpeg.org/downlo'+'ad.html</a><br><br><hr><br>' +
        'If the module stops downlo'+'ading videos, the "yt-dlp" version needs to be updated.<br>' +
        'This can happen at any time, so use the module wisely, but have a plan B.<br>',
    pt: 'Nunca foi tão fácil integrar vídeos/áudios das diversas plataformas ao seu acervo do Holyrics!<br>' +
        'Com este módulo, você pode baixar vídeos/áudios de maneira prática e eficiente, permitindo que conteúdos online estejam disponíveis para uso offline em suas apresentações ou transmissões.<br>' +
        'Utilizando o poderoso yt-dlp, uma ferramenta confiável e moderna, o módulo garante downlo'+'ads rápidos, qualidade personalizável e compatibilidade com diversos formatos.<br>' +
        'Tudo isso diretamente no Holyrics, com apenas alguns cliques!<br><hr>' +
        '<b>Modo de usar:</b> Clique no ícone "Baixar vídeo" do módulo na barra de módulos. <br>' +
        'Insira o link do vídeo, escolha as configurações desejadas e pronto! O vídeo será salvo automaticamente na pasta configurada.<br>' +
        '<b>Observação:</b> A velocidade do downlo'+'ad pode variar dependendo da sua conexão com a internet.<br>' +
        '<b>Requisitos:</b> yt-dlp e ffmpeg que podem ser baixados pela tela de configuração através de arquivos gerados pelo módulo nos sites:<br>' +
        '<a href="https://github.com/yt-dlp/yt-dlp/releases" target="_blank">"https://github.com/yt-dlp/yt-dlp/releases"</a>, e<br>' +
        '<a href="https://ffmpeg.org/downlo'+'ad.html" target="_blank">https://ffmpeg.org/downlo'+'ad.html</a><br><br><hr><br>' +
        'Se o módulo parar de baixar os vídeos, a versão do "yt-dlp" precisa ser atualizada.<br>' +
        'Isso pode ocorrer a qualquer momento, então utilize o módulo com sabedoria, mas tenha um plano B.<br>',
    ru: 'Никогда еще не было так просто интегрировать видео/аудио с различных платформ в вашу библиотеку Holyrics!<br>' +
        'С помощью этого модуля вы можете загружать видео/аудио быстро и эффективно, делая онлайн-контент доступным для офлайн-использования в ваших презентациях или трансляциях.<br>' +
        'Используя мощный yt-dlp, надежный и современный инструмент, модуль обеспечивает быструю загрузку, настраиваемое качество и совместимость с различными форматами.<br>' +
        'Все это прямо в Holyrics, всего за несколько кликов!<br><hr>' +
        '<b>Как использовать:</b> Нажмите на иконку "Скачать видео" модуля на панели модулей.<br>' +
        'Вставьте ссылку на видео, выберите нужные настройки, и готово! Видео будет автоматически сохранено в указанной папке.<br>' +
        '<b>Примечание:</b> Скорость загрузки может варьироваться в зависимости от вашего интернет-соединения.<br>' +
        '<b>Требования:</b> yt-dlp и ffmpeg можно скачать через экран настроек, используя файлы, сгенерированные модулем, с сайтов:<br>' +
        '<a href="https://github.com/yt-dlp/yt-dlp/releases" target="_blank">"https://github.com/yt-dlp/yt-dlp/releases"</a>, и<br>' +
        '<a href="https://ffmpeg.org/downlo'+'ad.html" target="_blank">https://ffmpeg.org/downlo'+'ad.html</a><br><br><hr><br>' +
        'Если модуль перестает загружать видео, необходимо обновить версию "yt-dlp".<br>' +
        'Это может произойти в любой момент, поэтому используйте модуль с умом, но имейте запасной план.<br>',
    es: '¡Nunca ha sido tan fácil integrar videos/audios de diversas plataformas en tu biblioteca de Holyrics!<br>' +
        'Con este módulo, puedes descargar videos/audios de manera práctica y eficiente, permitiendo que los contenidos en línea estén disponibles para su uso sin conexión en tus presentaciones o transmisiones.<br>' +
        'Usando la poderosa herramienta yt-dlp, confiable y moderna, el módulo garantiza descargas rápidas, calidad personalizable y compatibilidad con varios formatos.<br>' +
        '¡Todo esto directamente en Holyrics, con solo unos clics!<br><hr>' +
        '<b>Modo de uso:</b> Haz clic en el ícono "Descargar video" del módulo en la barra de módulos.<br>' +
        'Pega el enlace del video, elige las configuraciones deseadas y listo. El video se guardará automáticamente en la carpeta configurada.<br>' +
        '<b>Nota:</b> La velocidad de descarga puede variar dependiendo de tu conexión a internet.<br>' +
        '<b>Requisitos:</b> yt-dlp y ffmpeg se pueden descargar desde la pantalla de configuración utilizando archivos generados por el módulo desde los sitios:<br>' +
        '<a href="https://github.com/yt-dlp/yt-dlp/releases" target="_blank">"https://github.com/yt-dlp/yt-dlp/releases"</a>, y<br>' +
        '<a href="https://ffmpeg.org/downlo'+'ad.html" target="_blank">https://ffmpeg.org/downlo'+'ad.html</a><br><br><hr><br>' +
        'Si el módulo deja de descargar videos, será necesario actualizar la versión de "yt-dlp".<br>' +
        'Esto puede suceder en cualquier momento, así que utiliza el módulo con sabiduría, pero ten un plan B.<br>',
    it: 'Non è mai stato così facile integrare video/audio da varie piattaforme nella tua libreria di Holyrics!<br>' +
        'Con questo modulo, puoi scaricare video/audio in modo pratico ed efficiente, rendendo i contenuti online disponibili per l\'uso offline nelle tue presentazioni o trasmissioni.<br>' +
        'Utilizzando il potente yt-dlp, uno strumento affidabile e moderno, il modulo garantisce downlo'+'ad rapidi, qualità personalizzabile e compatibilità con vari formati.<br>' +
        'Tutto questo direttamente in Holyrics, con pochi clic!<br><hr>' +
        '<b>Come utilizzare:</b> Fai clic sull\'icona "Scarica video" del modulo nella barra dei moduli.<br>' +
        'Incolla il link del video, scegli le impostazioni desiderate, e il gioco è fatto! Il video sarà salvato automaticamente nella cartella configurata.<br>' +
        '<b>Nota:</b> La velocità di downlo'+'ad può variare a seconda della tua connessione internet.<br>' +
        '<b>Requisiti:</b> yt-dlp e ffmpeg possono essere scaricati dalla schermata di configurazione utilizzando file generati dal modulo dai siti:<br>' +
        '<a href="https://github.com/yt-dlp/yt-dlp/releases" target="_blank">"https://github.com/yt-dlp/yt-dlp/releases"</a>, e<br>' +
        '<a href="https://ffmpeg.org/downlo'+'ad.html" target="_blank">https://ffmpeg.org/downlo'+'ad.html</a><br><br><hr><br>' +
        'Se il modulo smette di scaricare video, sarà necessario aggiornare la versione di "yt-dlp".<br>' +
        'Questo può accadere in qualsiasi momento, quindi usa il modulo con saggezza, ma tieni un piano B.<br>'
});

    return arr;
}

 
 function i18n_getMap() {
    if (map) {
      return map;
    }
    map = {};
    var lang = h.getLanguage();
    i18n_getAllItems().forEach(function (o) {
        var k = o[defaultLang];
        map[k] = o[lang] ? o[lang] : k;
    });
    return map;
}

function i18n(candidate, arr) {
        var i18n_map = i18n_getMap();
        var str = i18n_map[candidate];
        var msg = (str != null ? str : candidate);
        if (arr == null || arr.length == null || arr.length == 0 || typeof arr === 'string') {
            return msg;
        }
        var placeHolder = "{}";
        var r = "";
        for (var current = 0, argIndex = 0; current < msg.length; ) {
            var token = msg.indexOf(placeHolder, current);
            if (token > -1) {
                r += msg.substring(current, token);
                r += arr[argIndex++];
                current = token + placeHolder.length();
            } else {
                r += msg.substring(current);
                break;
            }
        }
        return r;
}